### ISSUE TITLE
大佬，人脸识别那块代码可以加点注释么

### ISSUE THREAD

**Issue by liyang-love** [Raspberry-Monster/CheckInProject#1]
大佬，人脸识别那块代码可以加点注释么，越详细越好

**Comment by Raspberry-Monster** [comment]
https://github.com/takuya-takeuchi/FaceRecognitionDotNet
主要用的都是这边的实现
可以参考一下

**Comment by Raspberry-Monster** [comment]
主要我平常也没那么多时间来上注释 所以你可以把你不懂的地方写出在这个issue里或者是加我QQ 2194512339
我看到的话会找时间给你解答
